[*]
model = /home/$USER/repos/strix-halo-opencode/models/Qwen3.6-35B-A3B-Q8_0.gguf
jinja = true
top-k = 20
min-p = 0.0
repeat-penalty = 1.0
ctx-size = 262144
parallel = 2
n-gpu-layers = 999
flash-attn = 1
mmap = 0
host = 0.0.0.0
port = 11434

; Non-thinking mode for casual conversation
; Unsloth recommended: instruct (non-thinking) general tasks
[chatting]
chat-template-kwargs = {"enable_thinking":false}
reasoning = off
temp = 0.7
top-p = 0.8
presence-penalty = 1.5

; Non-thinking mode for task execution
; Qwen recommend: instruct (non-thinking) for reasoning tasks
[instruct]
chat-template-kwargs = {"enable_thinking":false}
reasoning = off
temp = 1.0
top-p = 0.95
top-k = 20
presence-penalty = 1.5

; Thinking mode for general tasks
; Unsloth recommended: thinking mode general tasks
[thinking]
chat-template-kwargs = {"enable_thinking":true, "preserve_thinking":true}
reasoning = on
temp = 1.0
top-p = 0.95
presence-penalty = 1.5

; Thinking mode tuned for precise coding
; Unsloth recommended: thinking mode precise coding tasks
[coding]
chat-template-kwargs = {"enable_thinking":true, "preserve_thinking":true}
reasoning = on
temp = 0.6
top-p = 0.95
presence-penalty = 0.0